### ISSUE TITLE
No "go back: functionality in Form mode

### ISSUE THREAD

**Issue by akrabat** [stoplightio/studio#498]
**Chore summary**
If I'm in "Form" mode and click "(go to ref)" in the schema in order to view/edit the referenced component, there is no way back to the schema that I came from.

**Tasks**
- [ ] Click on a Path in the left hand pane
- [ ] Click on the "(go to ref)" link to a component in the Schema section of the Request Body on the right hand side.
- [ ] Wonder how to get back to where you were.

**Additional context**
This is in the Mac desktop, version 2.0.0 (2.0.0.58956).

**Comment by philsturgeon** [comment]
Hey Rob, sorry to do this but we've consolidating feedback from 23473264 different places, including this soon-to-be-gone issue tracker, into this roadmap. You can vote for this feature and get notified when its done over here. https://roadmap.stoplight.io/4-stoplight-platform/c/140-native-browser-navigation
